blog/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
    # navigation urls
    # ---------------

    url(r'^$', views.blog, name="index"),
    # url(r'^home/$', views.home, name="home"),
    url(r'^trash/$', views.trash, name="trash"),
    url(r'^add/$', views.add, name="add"),

    # blog categories
    # ---------------
    url(r'^(?P<category>[\w]+)$', views.category, name="category"),

    # blog CRUD urls
    # --------------
    url(r'^(?P<post_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^(?P<post_id>[0-9]+)/trash_detail/$', views.trash_detail, name="trash_detail"),
    url(r'^(?P<post_id>[0-9]+)/edit/$', views.edit, name="edit"),
    url(r'^(?P<post_id>[0-9]+)/delete/$', views.delete, name="delete"),
    url(r'^(?P<post_id>[0-9]+)/delete_trash/$', views.delete_trash, name="delete_trash"),
    url(r'^(?P<post_id>[0-9]+)/comment/$', views.comment, name="comment"),
    url(r'^(?P<post_id>[0-9]+)/like/$', views.like, name="like"),
    url(r'^(?P<post_id>[0-9]+)/share/$', views.share, name="share"),

    # commenting system urls
    # ----------------------
    url(r'^edit_comment/(?P<comment_id>[0-9]+)/$', views.edit_comment, name="edit_comment"),
    url(r'^del_comment/(?P<comment_id>[0-9]+)/$', views.del_comment, name="del_comment"),

    # user management
    # -----------------
    url(r'^sign_up/$', views.sign_up, name="sign_up"),
    url(r'^user_login/$', views.user_login, name="user_login"),
    url(r'^user_logout/$', views.user_logout, name="user_logout"),
    url(r'^users/(?P<user_id>[0-9]+)/$', views.user_profile, name="profile"),
    url(r'^users/edit_profile/(?P<user_id>[0-9]+)/$', views.edit_profile, name="edit_profile"),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tuxfun/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'tuxfun.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', 'blog.views.home', name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# custom user class
class Author(AbstractUser):
    image = models.ImageField(null=True, upload_to='user/%Y/%m/%d')


class Post(models.Model):
    post_title = models.CharField(max_length=255)
    post_text = models.TextField()
    pub_date = models.DateTimeField()
    mod_date = models.DateTimeField()
    active  = models.BooleanField(default = True)
    category = models.CharField(max_length=50, default="linux")
    likes = models.IntegerField(default=0)
    shares = models.IntegerField(default=0)
    image = models.ImageField(blank=True, default='', upload_to= 'post/%Y/%m/%d/')
    author = models.ForeignKey(Author)

    def __unicode__(self):
        return self.post_title

class Comment(models.Model):
    comment_text = models.CharField(max_length=140)
    pub_date = models.DateTimeField()
    mod_date = models.DateField()
    post = models.ForeignKey(Post)
    active = models.BooleanField(default = True)

    def __unicode__(self):
        return self.comment_text

blog/forms.py
from django import forms
from .models import Post, Author
from django.contrib.auth.models import User, AbstractUser
from django.contrib.auth import forms as auth_forms

CATEGORY_CHOICES = (
    ('linux','Linux'),
    ('programming', 'Programming'),
    ('web', 'Web'),
    ('thoughts','Thoughts'),
    ('fun','Fun'),
)

class SampleForm(forms.Form):
    CATEGORY_CHOICES = (
        ('Linux','linux'),
        ('Programming', 'programming'),
        ('Web', 'web'),
    )
    title = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    blog_post = forms.CharField(required=True, widget=forms.Textarea(attrs={'class':'form-control'}))

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title','category','image','post_text']
        widgets = {
            "post_title":forms.TextInput(attrs={'class':'form-control'}),
            "category":forms.Select(choices=CATEGORY_CHOICES, attrs={'class':'form-control'}),
            "post_text":forms.Textarea(attrs={'class':'form-control','cols':'10'})
        }

class EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_title','image','post_text']
        widgets = {
            "post_title":forms.TextInput(attrs={'class':'form-control'}),
            "post_text":forms.Textarea(attrs={'class':'form-control'})
        }

class NewUserForm(auth_forms.UserCreationForm):

    class Meta:
        model = Author
        fields = ("username","email")
        # widgets = {
        #     "first_name":forms.TextInput(attrs={'class':'form-control'}),
        #     "last_name":forms.TextInput(attrs={'class':'form-control'}),
        #     "username":forms.TextInput(attrs={'class':'form-control'}),
        #     "email":forms.TextInput(attrs={'class':'form-control', 'type':'email'}),
        #     # "password1":forms.PasswordInput(attrs={'class':'form-control'}),
        #     # "password2":forms.PasswordInput(attrs={'class':'form-control'}),
        # }
    def __init__(self, *args, **kwargs):

        super(NewUserForm, self).__init__(*args, **kwargs)
        # print self.fields
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            # self.fields['username'].widget.attrs['class'] = 'form-control'
            # self.fields['password1'].widget.attrs['class'] = 'form-control'
            # self.fields['password2'].widget.attrs['class'] = 'form-control'

class LoginForm(forms.Form):
    username = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'type':'password'}))

class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ['username','first_name','last_name','email','image']
        # exclude = ['password','is_active','is_staff','is_superuser','user_permissions','groups']

    def __init__(self, *args, **kwargs):

        super(EditProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
            self.fields[field].widget.attrs['required'] = True

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from .forms import PostForm, EditPostForm, NewUserForm, LoginForm, EditProfileForm
from .models import Post, Comment, Author
from django.core.paginator import Paginator, EmptyPage, InvalidPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def blog(request):
    posts_list = Post.objects.filter(active=1).order_by('-pub_date')
    paginator = Paginator(posts_list, 5)

    try:
        page = int(request.GET.get("page", 1))

    except:
        page = 1

    try:
        posts = paginator.page(page)

    except(EmptyPage, InvalidPage, PageNotAnInteger):
        posts = paginator.page(paginator.num_pages)

    # breadcrumb feed
    link = reverse('home')
    link1 = reverse('blog:index')

    # block aside feeds
    recent_5_posts = Post.objects.filter(active=1).order_by('-pub_date')[:5]
    recent_5_fun = Post.objects.filter(active=1, category='fun').order_by('-pub_date')[:5]

    context = {'posts': posts, 'recent_5_posts': recent_5_posts,
               'recent_5_fun': recent_5_fun,
               }

    return render(request, 'blog/index.html', context)


def home(request):
    recent_5_posts = Post.objects.filter(active=1).order_by('-pub_date')[:5]
    recent_5_fun = Post.objects.filter(active=1, category='fun').order_by('-pub_date')[:5]

    context = {'recent_5_posts': recent_5_posts,
               'recent_5_fun': recent_5_fun,
               }

    return render(request, 'blog/home.html', context)


@login_required(login_url='/blog/user_login/')
def trash(request):
    posts_list = Post.objects.filter(active=0).order_by('-pub_date')
    paginator = Paginator(posts_list, 5)

    try:
        page = int(request.GET.get("page", 1))

    except:
        page = 1

    try:
        posts = paginator.page(page)

    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    recent_5_posts = Post.objects.filter(active=1).order_by('-pub_date')[:5]
    recent_5_fun = Post.objects.filter(active=1, category='fun').order_by('-pub_date')[:5]

    context = {'posts': posts, 'recent_5_posts': recent_5_posts,
               'recent_5_fun': recent_5_fun,
               'posts': posts
               }

    return render(request, 'blog/trash.html', context)


def category(request, category):
    posts_list = Post.objects.filter(active=1, category=category).order_by('-pub_date')
    paginator = Paginator(posts_list, 5)

    try:
        page = int(request.GET.get("page", 1))

    except:
        page = 1

    try:
        posts = paginator.page(page)

    except(EmptyPage, InvalidPage):
        posts = paginator.page(paginator.num_pages)

    # breadcrumb feed
    link = reverse('home')
    link1 = reverse('blog:index')

    # block aside feeds
    recent_5_posts = Post.objects.filter(active=1).order_by('-pub_date')[:5]
    recent_5_fun = Post.objects.filter(active=1, category='fun').order_by('-pub_date')[:5]

    context = {'posts': posts, 'recent_5_posts': recent_5_posts,
               'recent_5_fun': recent_5_fun,
               }

    return render(request, 'blog/category.html', context)


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comment_set.filter(active=1).order_by('-pub_date')
    recent_5_posts = Post.objects.filter(active=1).order_by('-pub_date')[:5]
    recent_5_fun = Post.objects.filter(active=1, category='fun').order_by('-pub_date')[:5]

    context = {'recent_5_posts': recent_5_posts,
               'recent_5_fun': recent_5_fun,
               'post': post,
               'comments': comments,
               }

    return render(request, 'blog/detail.html', context)


@login_required(login_url='/blog/user_login/')
def trash_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comment_set.filter(active=1).order_by('-pub_date')
    recent_5_posts = Post.objects.filter(active=1).order_by('-pub_date')[:5]
    recent_5_fun = Post.objects.filter(active=1, category='fun').order_by('-pub_date')[:5]

    context = {'recent_5_posts': recent_5_posts,
               'recent_5_fun': recent_5_fun,
               'post': post,
               'comments': comments,
               }

    return render(request, 'blog/trash_detail.html', context)


@login_required(login_url='/blog/user_login/')
def add(request):
    recent_5_posts = Post.objects.filter(active=1).order_by('-pub_date')[:5]
    recent_5_fun = Post.objects.filter(active=1, category='fun').order_by('-pub_date')[:5]

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = get_object_or_404(Author, pk=request.user.id)
            post.pub_date = timezone.now()
            post.mod_date = timezone.now()
            post.save()

            return redirect(reverse('blog:index'))
        else:
            form = PostForm()
            return render(request, 'blog/add.html', {'form': form})

    else:
        form = PostForm()
        context = {'recent_5_posts': recent_5_posts,
                   'recent_5_fun': recent_5_fun,
                   'form': form
                   }
        return render(request, 'blog/add.html', context)


@login_required(login_url='/blog/user_login/')
def edit(request, post_id):
    now = timezone.now()
    post = Post.objects.get(pk=post_id)
    recent_5_posts = Post.objects.filter(active=1).order_by('-pub_date')[:5]
    recent_5_fun = Post.objects.filter(active=1, category='fun').order_by('-pub_date')[:5]

    if request.method == "POST":
        form = EditPostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.pub_date = now
            post.save()

            return redirect(reverse('blog:detail', args=(post.id,)))

    else:
        form = EditPostForm(instance=post)
        context = {'recent_5_posts': recent_5_posts,
                   'recent_5_fun': recent_5_fun,
                   'form': form
                   }
        return render(request, 'blog/edit.html', context)


@login_required(login_url='/blog/user_login/')
def delete(request, post_id):
    post = Post.objects.get(pk=post_id)
    post.active = False
    post.save()
    return redirect(reverse('blog:index'))


@login_required(login_url='/blog/user_login/')
def delete_trash(request, post_id):
    # article is lost for good
    post = get_object_or_404(Post, pk=post_id)
    post.delete()

    return redirect(reverse('blog:index'))


@login_required(login_url='/blog/user_login/')
def comment(request, post_id):
    if request.method == "GET":
        return redirect(reverse('blog:detail', args=(post_id,)))

    elif request.method == "POST":
        now = timezone.now()
        post = get_object_or_404(Post, pk=post_id)
        post.comment_set.create(comment_text=request.POST['comment'], pub_date=now, mod_date=now)

        return redirect(reverse('blog:detail', args=(post.id,)))


@login_required(login_url='/blog/user_login/')
def like(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.likes += 1
    post.save()
    return redirect(reverse('blog:detail', args=(post.id,)))


@login_required(login_url='/blog/user_login/')
def share(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.pub_date = timezone.now()
    post.shares += 1
    post.save()
    return redirect(reverse('blog:detail', args=(post.id,)))


@login_required(login_url='/blog/user_login/')
def edit_comment(request, comment_id):
    now = timezone.now()
    comment = Comment.objects.get(pk=comment_id)
    post_id = comment.post_id
    if request.method == "GET":
        return render(request, 'blog/edit_comment.html', {'comment': comment})

    else:
        comment.comment_text = request.POST['comment']
        comment.mod_date = now
        comment.save()
        return redirect(reverse('blog:detail', args=(post_id,)))


@login_required(login_url='/blog/user_login/')
def del_comment(request, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    post_id = comment.post_id
    comment.active = False
    comment.save()
    return redirect(reverse('blog:detail', args=(post_id,)))


# user management
# -----------------
def sign_up(request):
    form = NewUserForm()
    if request.method == 'GET':
        return render(request, 'blog/sign_up.html', {'form': form})
    else:
        form = NewUserForm(request.POST)
        if form.is_valid():
            # first_name = form.cleaned_data['first_name']
            # last_name = form.cleaned_data['last_name']
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.clean_password2()

            if password:
                form.save()
                return redirect(reverse('blog:index'))
            else:
                form = NewUserForm()
                return render(request, 'blog/sign_up.html', {'form': form})
        else:
            form = NewUserForm()
            return render(request, 'blog/sign_up.html', {'form': form})


def user_login(request):
    form = LoginForm()
    if request.method == "GET":
        return render(request, 'blog/login.html', {'form': form})
    else:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None and user.is_active:
            login(request, user)
            return redirect(reverse('blog:index'))
        else:
            return redirect(reverse('blog:user_login'))


def user_logout(request):
    logout(request)

blog/templates/blog/add.html
{% extends 'blog/base.html' %}
{% load staticfiles %}

{% block content %}
  <article>
    {% for field in form %}
      <p>{{ field.error }}</p>
    {% endfor %}
    <form action="{% url 'blog:add' %}" method="post"  enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button class=" form-control btn btn-info" type='submit'>Publish</button>
    </form>
  </article>

{% endblock %}

blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tuxfun Home - Linux and Programming News</title>
    <link rel='stylesheet' href="{% static 'blog/bootstrap/bootstrap.min.css' %}" >
    <link rel='stylesheet' href="{% static 'blog/main.css' %}">
    <meta charset="utf-8">
  </head>
  <body>

    <header>
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#blog-menu">
            <span class="sr-only">Menu</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">TuxFun</a>
        </div>

        <div class="collapse navbar-collapse" id="blog-menu">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
            <li><a href="{% url 'blog:index' %}"><span class="glyphicon glyphicon-time"></span> Recent</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Category<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'blog:category' 'linux' %}"><span class="glyphicon glyphicon-cog"></span> Linux</a></li>
                <li><a href="{% url 'blog:category' 'programming' %}"><span class="glyphicon glyphicon-stats"></span> Programming</a></li>
                <li><a href="{% url 'blog:category' 'web' %}"><span class="glyphicon glyphicon-globe"></span> Web</a></li>
                <li class="divider"></li>
                <li><a href="{% url 'blog:category' 'thoughts' %}"><span class="glyphicon glyphicon-flag"></span> Thoughts</a></li>
                <li><a href="{% url 'blog:category' 'fun' %}"><span class="glyphicon glyphicon-user"></span> Fun</a></li>
              </ul>
            </li>
            <li><a href="{% url 'blog:add' %}"><span class="glyphicon glyphicon-add"></span> Add Blog</a></li>
            <li><a href="{% url 'blog:trash' %}"><span class="glyphicon glyphicon-trash"></span> Trash</a></li>

          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if request.user.id %}
                  <li><a href="{% url 'blog:profile' request.user.id %}"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
              {% endif %}
            {# {% if request.user %}#}
              <li><a href="{% url 'blog:user_login' %}"><span class="glyphicon glyphicon-inbox"></span> Login</a></li>
            {# {% else %}#}
              <li><a href="{% url 'blog:sign_up' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
              <li><a href="{% url 'blog:user_logout' %}"><span class="glyphicon glyphicon-inbox"></span> Logout</a></li>
            {# {% endif %}#}
          </ul>
        </div>

      </nav>

    </header>

    <div class="page-header">
      <div class="container">
        <p class="alert alert-success">
          {% if request.user %}
            Welcome {{ request.user }}
          {% else %}
            Welcome Anonymous!
          {% endif %}
        </p>
      </div>
    </div>

      <div class="container">

        <!-- <ul class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li><a href="#">Blog</a></li>
        </ul> -->

        <div class="row">
          <div class="col-md-3">
              {% block aside %}

              {% endblock %}
          </div>
          <div class="col-md-6">
            {% block content %}

            {% endblock %}
          </div>

          <div class="col-md-3">

            {% block aside1 %}
              <h2>Popular on Tuxfun</h2>
              {% if recent_5_posts %}
                {% for post in recent_5_posts %}
                  <p><a href="{% url "blog:detail" post.id %}">{{ post.post_title }}</a></p>
                {% endfor %}
              {% else %}
                <p>No posts yet<a href="{% url 'blog:add' %}">Add One!</a></p>
              {% endif %}

              <h2>Popular fun articles</h2>
              {% if recent_5_fun %}
                {% for post in recent_5_fun  %}
                  <p><a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></p>
                {% endfor %}
              {% else %}
               <p>No fun posts! <a href="{% url 'blog:add' %}">Add One!</a></p>
              {% endif %}
            {% endblock %}
          </div>

        </div>

      </div>

    </div>
    <script src="{% static 'blog/jquery.min.js' %}"></script>
    <script src="{% static 'blog/bootstrap/bootstrap.min.js' %}"></script>

  </body>
</html>

blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
  <article>
    {% if post %}
        <content>
          <h3>{{ post.id }}: <a href="{% url 'blog:detail' post.id %}">{{ post.post_title }}</a></h3>
          <small><strong>Posted {{ post.pub_date }} </small></strong>
          in <a href="{% url 'blog:category' post.category %}">{{ post.category|lower }} </a> |
          <a href="{% url 'blog:edit' post.id  %}" title="Edit Post"><span class="glyphicon glyphicon-pencil"></span> Edit Post</a> |
          <a href="{% url 'blog:delete' post.id %}"><span class="glyphicon glyphicon-trash"></span> Delete</a> <br>
        </content>
        <content>
          {% if post.image.url != none %}
          <img class="thumbnail" src={{ post.image.url }} height="" width="100%" title="post title" alt="make the post more attractive">
          {% endif %}
          <p>{{ post.post_text }}<p><br>
        </content>
        <content>
          <p>
             <a class="glyph-link" href="{% url 'blog:like' post.id %}"><span title="love" class="glyphicon glyphicon-heart-empty"> <small>{{ post.likes }}</small></span></a>
             <a class="glyph-link" href="{% url 'blog:comment' post.id %}"><span class="glyphicon glyphicon-comment"> <small>{{ post.comment_set.count }}</small></span></a>
             <a class="glyph-link" href="{% url 'blog:share' post.id %}"><span class="glyphicon glyphicon-retweet"> <small>{{ post.shares }}</small></span></a>
          </p>
          <hr>
        </content>


      {% block comment_form %}
      <form action="{% url 'blog:comment' post.id %}" method="post">
        {% csrf_token %}
        <input class="form-control" type="text" name="comment" placeholder="comment..." required><br>
        <button class="form-control btn btn-info" type="submit">Publish</button>
      </form>
      {% endblock %}

      <section class="comment-section">
        <h4>{{ post.comment_set.count }} Comments & Reactions</h4><hr>
        {% if post.comment_set.all.0 != None %}
          {% for comment in comments %}
            <p class="comment-comment">{{ comment.comment_text }} <strong><small>{{ comment.pub_date }}</small></strong>
                 <a href="{% url 'blog:edit_comment' comment.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                 <a href="{% url 'blog:del_comment' comment.id %}"><span class="glyphicon glyphicon-trash"></span></a>
            </p>
          {% endfor %}
        {% else %}
          <p>Be the first to respond</p>
        {% endif %}
      </section>
    {% else %}
      <p>Post not found.Back <a href="{% url 'blog:index' %}">Home</a> </p>
    {% endif %}
  </article>

{% endblock %}

blog/templates/blog/edit.html
{% extends 'blog/index.html' %}
{% load staticfiles %}

{% block content %}
  {% if form %}
    <article>
      <form action="." method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="form-control btn btn-info" type="submit">Publish</button>
      </form>
    </article>
  {% else %}
    <p>Send Default Data to form</p>
  {% endif %}

{% endblock %}

blog/templates/blog/edit_comment.html
{% extends 'blog/index.html' %}
{% load staticfiles %}

{% block content %}
	<form action="{% url 'blog:edit_comment' comment.id %}" method="post">
		{% csrf_token %}
		<input class="form-control" type="text" name="comment" value="{{ comment.comment_text }}" required><br>
		<button class="form-control btn btn-info" type="submit">Publish</button>
	</form>
{% endblock %}

blog/templates/blog/form_test.html
{% extends "blog/base.html" %}
{% block content %}
    <form class="form-group" action={% url 'blog:form_test' %} method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class=" form-control btn btn-info" type='submit'>Publish</button>
    </form>
{% endblock %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block content %}

      <div class='jumbotron'>
        <h1>You are at Tuxfun!</h1>
        <p>Here, Programming, Linux, OpenSource and the Web are Always Fun!</p>
        <button class="btn btn-link btn-info"><a href="{% url 'blog:index' %}">Learn more</a></button>
      </div>

{% endblock %}

blog/templates/blog/sign_up.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block content %}
  <article>
    {% for field in form.fields %}
      <p>{{ field.error }}</p>
    {% endfor %}
    <form class="form-group" action="{% url 'blog:sign_up' %}" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-info form-control">Sign Up</button>
    </form>
  </article>
{% endblock %}

blog/templates/blog/trash_detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block content %}
  <article>
    {% if post %}
        <content>
          <h3>{{ post.id }}: <a href="{% url 'blog:trash_detail' post.id %}">{{ post.post_title }}</a></h3>
          <small><strong>Posted {{ post.pub_date }} </small></strong>
          in <a href="{% url 'blog:category' post.category %}">{{ post.category|lower }} </a> |
          <a href="{% url 'blog:edit' post.id  %}" title="Edit Post"><span class="glyphicon glyphicon-pencil"></span> Edit Post</a> |
          <a href="{% url 'blog:delete_trash' post.id %}"><span class="glyphicon glyphicon-trash"></span> Delete</a> <br>
        </content>
        <content>
          <img class="thumbnail" src={{ post.image.url }} height="50%" width="50%" title="post title" alt="make the post more attractive">
          <p>{{ post.post_text }}<p><br>
        </content>
        <content>
          <p>
             <a class="glyph-link" href="{% url 'blog:like' post.id %}"><span title="love" class="glyphicon glyphicon-heart-empty"> <small>{{ post.likes }}</small></span></a>
             <a class="glyph-link" href="{% url 'blog:comment' post.id %}"><span class="glyphicon glyphicon-comment"> <small>{{ post.comment_set.count }}</small></span></a>
             <a class="glyph-link" href="{% url 'blog:share' post.id %}"><span class="glyphicon glyphicon-retweet"> <small>{{ post.shares }}</small></span></a>
          </p>
          <hr>
        </content>


      {% block comment_form %}
      <form action="{% url 'blog:comment' post.id %}" method="post">
        {% csrf_token %}
        <input class="form-control" type="text" name="comment" placeholder="comment..." required><br>
        <button class="form-control btn btn-info" type="submit">Publish</button>
      </form>
      {% endblock %}

      <section class="comment-section">
        <h4>{{ post.comment_set.count }} Comments & Reactions</h4><hr>
        {% if post.comment_set.all.0 != None %}
          {% for comment in comments %}
            <p class="comment-comment">{{ comment.comment_text }} <strong><small>{{ comment.pub_date }}</small></strong>
                 <a href="{% url 'blog:edit_comment' comment.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
                 <a href="{% url 'blog:del_comment' comment.id %}"><span class="glyphicon glyphicon-trash"></span></a>
            </p>
          {% endfor %}
        {% else %}
          <p>Be the first to respond</p>
        {% endif %}
      </section>
    {% else %}
      <p>Post not found.Back <a href="{% url 'blog:index' %}">Home</a> </p>
    {% endif %}
  </article>

{% endblock %}